---
- name: restart php-fpm
  service: name={{ php_fpm_service_name }} state=restarted
  when: php_fpm_started

- name: reload php-fpm
  service: name={{ php_fpm_service_name }} state=reloaded
  when: php_fpm_started
